# Define base image
FROM ubuntu:jammy-20230804

# Install needed apt software
RUN apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-pip python3.10-venv git ffmpeg libsm6 libxext6

# Create non-root user
USER root
RUN groupadd -g 5500 appgroup && useradd -u 5500 -g appgroup appuser

WORKDIR /app
RUN mkdir -p /app && chown appuser:appgroup /app
USER appuser

# Configure virtual environment.
ENV VIRTUAL_ENV=/app/.local/venv
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Pip configuration and installation of dependencies
ENV PIP_CACHE_DIR=/app/.local/cache/pip
COPY requirements_aidreaming.txt /app/requirements.txt
RUN python3 -m pip install -r /app/requirements.txt

USER root
RUN mkdir -p /app/external_models && chown -R appuser:appgroup /app/external_models
# Not sure if I should build these into the image or volume mount.
COPY --chown=appuser:appgroup Fooocus/models /app/models
COPY --chown=appuser:appgroup Fooocus/modules /app/modules
USER appuser

COPY Fooocus/ldm_patched /app/ldm_patched
COPY Fooocus/sdxl_styles /app/sdxl_styles
COPY Fooocus/javascript /app/javascript
COPY Fooocus/css /app/css
COPY Fooocus/extras /app/extras
# Python program to run in the container
COPY Fooocus/entry_with_update.py /app/
COPY Fooocus/fooocus_version.py /app/
COPY Fooocus/build_launcher.py /app/
COPY Fooocus/args_manager.py /app/
COPY Fooocus/launch.py /app/
COPY Fooocus/shared.py /app/
COPY Fooocus/webui.py /app/
COPY Fooocus/LICENSE /app/
COPY Fooocus/requirements_versions.txt /app/

## Docker does not support overlays 
 # Will Symlink Models in /app/external_models into /app/models without overriding contents in /app/models 
 # on entry 
COPY entrypoint.sh entrypoint.sh
#cache loctions
ENV MPLCONFIGDIR=/app/.local/cache/matplotlib
ENV TRANSFORMERS_CACHE=/app/.local/cache/huggingface/hub

ENTRYPOINT [ "/app/entrypoint.sh" ]
