# define base image
FROM ubuntu:jammy-20230804

# Install needed apt software
RUN apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-pip python3.10-venv

# Create non-root user
USER root
RUN groupadd -g 5500 appgroup && useradd -u 5500 -g appgroup appuser

WORKDIR /app
RUN mkdir -p /app && chown appuser:appgroup /app
USER appuser

# Configure virtual environment.
ENV VIRTUAL_ENV=/app/.local/venv
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Pip configuration and installation of dependencies
ENV PIP_CACHE_DIR=/app/.local/cache/pip

# Python program to run in the container
COPY reaper.py /app/

ENTRYPOINT [ "python3", "/app/reaper.py" ]
