# Define base image
FROM ubuntu:jammy-20230804

# Install needed apt software
RUN apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-pip python3.10-venv git

# Create non-root user
USER root
RUN groupadd -g 5500 appgroup && useradd -u 5500 -g appgroup appuser

WORKDIR /app
RUN mkdir -p /app && chown appuser:appgroup /app
USER appuser

# Configure virtual environment.
ENV VIRTUAL_ENV=/app/.local/venv
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Pip configuration and installation of dependencies
ENV PIP_CACHE_DIR=/app/.local/cache/pip
COPY requirements_versions.txt /app/
RUN python3 -m pip install -r /app/requirements_versions.txt

# Git clone with specific directory as that is what the original repo did
RUN mkdir /app/repositories && cd /app/repositories \
    && git clone https://github.com/comfyanonymous/ComfyUI ComfyUI-from-StabilityAI-Official \
    && cd /app/repositories/ComfyUI-from-StabilityAI-Official \
    && git checkout 2bc12d3d22efb5c63ae3a7fc342bb2dd16b31735

ENV PATH="/app/repositories/ComfyUI:${PATH}"

RUN mkdir -p /app/modules
RUN mkdir -p /app/models
# Not sure if I should build these into the image or volume mount.
COPY models /app/models
COPY modules /app/modules

# Python program to run in the container
COPY entry_with_update.py /app/
COPY fooocus_version.py /app/
COPY launch.py /app/
COPY shared.py /app/
COPY webui.py /app/
COPY LICENSE /app/

#cache loctions
ENV MPLCONFIGDIR=/app/.local/cache/matplotlib
ENV TRANSFORMERS_CACHE=/app/.local/cache/huggingface/hub

ENTRYPOINT [ "python3", "/app/launch.py", "--listen" ]